### ISSUE TITLE
[maven-plugin] no "serializableModel" option in swagger-codegen-maven-plugin available

### ISSUE THREAD

**Issue by markusdent** [swagger-api/swagger-codegen#10106]
##### Description

As the title suggested is there no option to add "implements Serializable" for the generated models in the maven-plugin, like it is in the normal cli with serializableModel=true.

##### Swagger-codegen version

I tried 
``` 
<groupId>io.swagger</groupId>
<artifactId>swagger-codegen-maven-plugin</artifactId>
<version>2.3.1</version> ```

and 

````
<groupId>io.swagger.codegen.v3</groupId>
<artifactId>swagger-codegen-maven-plugin</artifactId>
 <version>3.0.18</version>
```

##### Command line used for generation

No command line, but build with maven. There the option is missing.

##### Steps to reproduce

Try to set the option in the config in maven pom.xml 

##### Suggest a fix/enhancement

Add this option to the maven-plugin?  It is already there in the cli, so I think it can be easily done?

**Comment by moghaffari** [comment]
@markusdent Have you tried the following?
```
<configuration>
     ...
   <configOptions>
         <serializableModel>true</serializableModel>
   </configOptions>
</configuration>
```

**Comment by vrmoreira** [comment]
@moghaffari , just hijacking this thread: using version "2.3.1" of the plugin, the generated code implements `Serializable` with your suggestion.

Thanks for the tip and, IMHO, this issue is resolved.

**Comment by lolwa796** [comment]
@vrmoreira 

I am not seeing the code available in the tag v2.3.1,  
https://github.com/swagger-api/swagger-codegen/blob/v2.3.1/modules/swagger-codegen/src/main/resources/JavaJaxRS/cxf/pojo.mustache

I feel its still not resolved. 

The below PR do resolve it, but looks like its behind base branch 
https://github.com/swagger-api/swagger-codegen/pull/9453

Can we create a new PR with the  above changes,or  @peetie2k - can you please update  ?
