### ISSUE TITLE
Generate client HTML2 - parameter with hyphen

### ISSUE THREAD

**Issue by webron** [swagger-api/swagger-codegen#4864]
_From @ChristianKoessl on February 27, 2017 17:16_

**Swagger File**

```yaml
swagger: '2.0'
info:
  version: '1.0'
  description: API
  title: API
schemes:
  - https
paths:
  /cnbs/oauth:
    post:
      description: Get authroization token
      operationId: authorize
      produces:
        - application/json
      parameters:
        - name: sap-client
          in: query
          description: SAP client
          required: true
          type: integer
          maximum: 999
        - name: apiid
          in: query
          description: API ID
          required: true
          type: string
        - name: API-SysID
          in: header
          description: System ID
          required: true
          type: string
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/authResponse'
        default:
          description: Error
          schema:
            $ref: '#/definitions/authResponse'
      security:
        - basicAuth: []
securityDefinitions:
  basicAuth:
    type: basic
    description: User and Password
definitions:
  authResponse:
    type: object
    properties:
      access_token:
        type: string
      token_type:
        type: string
      expires_in:
        type: integer
        maximum: 9999
      status:
        $ref: '#/definitions/status'
  status:
    type: object
    properties:
      msgty:
        type: string
        maxLength: 1
      msgid:
        type: string
        maxLength: 20
      msgno:
        type: integer
        maximum: 999
      msgln:
        type: string
```

* Version: 
* Browser/OS: 

**Issue**
I am using online version from swagger editor. When I am generating HTML2 client coding, query parameter name "sap-client" is changed to "sapClient". When I generate HTML client coding, parameter name "sap-client" is unchanged. For a SAP system, parameter must be named as "sap-client". 

kind regards
Christian
 

_Copied from original issue: swagger-api/swagger-editor#1199_

**Comment by ePaul** [comment]
I would guess that this is the same underlying issue as #1219 (for spring/spring-mvc), where the parameter name is mangled to camelCase, too.

**Comment by wing328** [comment]
@ChristianKoessl the issue should have been addressed via https://github.com/swagger-api/swagger-codegen/pull/4602. Please pull the latest master to give it a try.

**Comment by ChristianKoessl** [comment]
Hi wing328,

just installed swagger-editor version 2.10.5. When I am generating the HTML2 client, parameter name changing is still active.

kind regards
Christian

**Comment by wing328** [comment]
@ChristianKoessl swagger-editor and swagger-codegen are 2 separate projects: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#what-does-httpseditorswaggerio-leverage-swagger-codegen-for-code-generation

We'll release v2.2.2 of Swagger Codegen soon and update generator.swagger.io to run v2.2.2.

**Comment by ChristianKoessl** [comment]
Hi,

 
fyi, the parameter name in the generated HTML2 document are now correct, but the name in the examples still shows the name without hyphen.

 

 
kind regards

Christian

 
Von: wing328 [mailto:notifications@github.com] 
Gesendet: Mittwoch, 1. März 2017 14:00
An: swagger-api/swagger-codegen <swagger-codegen@noreply.github.com>
Cc: Christian Kössl <christian.koessl@koessl.co.at>; Mention <mention@noreply.github.com>
Betreff: Re: [swagger-api/swagger-codegen] Generate client HTML2 - parameter with hyphen (#4864)

 
@ChristianKoessl swagger-editor and swagger-codegen are 2 separate projects: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#what-does-httpseditorswaggerio-leverage-swagger-codegen-for-code-generation

We'll release v2.2.2 of Swagger Codegen soon and update generator.swagger.io to run v2.2.2.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/swagger-api/swagger-codegen","title":"swagger-api/swagger-codegen","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/swagger-api/swagger-codegen"}},"updates":{"snippets":[{"icon":"PERSON","message":"@wing328 in #4864: @ChristianKoessl swagger-editor and swagger-codegen are 2 separate projects: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#what-does-httpseditorswaggerio-leverage-swagger-codegen-for-code-generation\r\n\r\nWe'll release v2.2.2 of Swagger Codegen soon and update generator.swagger.io to run v2.2.2."}],"action":{"name":"View Issue","url":"https://github.com/swagger-api/swagger-codegen/issues/4864#issuecomment-283333341"}}}

**Comment by wing328** [comment]
@ChristianKoessl Ok. I've reopened this issue.

Would you have time to contribute a fix?

**Comment by ChristianKoessl** [comment]
Hi,

 
I am notes sure what you mean with “contribute a fix”? Do you mean by changing coding of the codgen source? I am not JAVA developer, don’t think that I am able to fix it

 
Mfg

Christian Kössl

 
Von: wing328 [mailto:notifications@github.com] 
Gesendet: Freitag, 3. März 2017 10:34
An: swagger-api/swagger-codegen <swagger-codegen@noreply.github.com>
Cc: Christian Kössl <christian.koessl@koessl.co.at>; Mention <mention@noreply.github.com>
Betreff: Re: [swagger-api/swagger-codegen] Generate client HTML2 - parameter with hyphen (#4864)

 
@ChristianKoessl Ok. I've reopened this issue.

Would you have time to contribute a fix?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/swagger-api/swagger-codegen","title":"swagger-api/swagger-codegen","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/swagger-api/swagger-codegen"}},"updates":{"snippets":[{"icon":"PERSON","message":"@wing328 in #4864: @ChristianKoessl Ok. I've reopened this issue.\r\n\r\nWould you have time to contribute a fix?"}],"action":{"name":"View Issue","url":"https://github.com/swagger-api/swagger-codegen/issues/4864#issuecomment-283908391"}}}

**Comment by wing328** [comment]
You don't need to know Java. The mustache templates for `html` can be found in https://github.com/swagger-api/swagger-codegen/tree/master/modules/swagger-codegen/src/main/resources/htmlDocs2

**Comment by ChristianKoessl** [comment]
Hi,

 
just checked these templates. I unfortunately cannot contribute for a fixing. I am not familiar with the way how these codegen project is working. I am afraid I would destroy more than do a fixing, sorry!

 
Mfg

Christian Kössl

 
Von: wing328 [mailto:notifications@github.com] 
Gesendet: Freitag, 3. März 2017 10:44
An: swagger-api/swagger-codegen <swagger-codegen@noreply.github.com>
Cc: Christian Kössl <christian.koessl@koessl.co.at>; Mention <mention@noreply.github.com>
Betreff: Re: [swagger-api/swagger-codegen] Generate client HTML2 - parameter with hyphen (#4864)

 
You don't need to know Java. The mustache templates for html can be found in https://github.com/swagger-api/swagger-codegen/tree/master/modules/swagger-codegen/src/main/resources/htmlDocs2

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/swagger-api/swagger-codegen","title":"swagger-api/swagger-codegen","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/swagger-api/swagger-codegen"}},"updates":{"snippets":[{"icon":"PERSON","message":"@wing328 in #4864: You don't need to know Java. The mustache templates for `html` can be found in https://github.com/swagger-api/swagger-codegen/tree/master/modules/swagger-codegen/src/main/resources/htmlDocs2"}],"action":{"name":"View Issue","url":"https://github.com/swagger-api/swagger-codegen/issues/4864#issuecomment-283910465"}}}

**Comment by wing328** [comment]
No worry. I've marked this as "Need community contribution" so that the community can help contribute the fix.
