### ISSUE TITLE
Enums: @JsonValue annotation is missing from toString() in the generated model for language jaxrs

### ISSUE THREAD

**Issue by deveshpujari** [swagger-api/swagger-codegen#6587]
Looked at issue #3611 #3615 

It does not work for language jaxrs .
I tried using 2.2.3 and 2.3.0 lastest snapshot also.

java -jar swagger-codegen-cli-2.3.0.jar generate -i genapi.yaml -l jaxrs -o generated_server

public enum HealthType {

OVERALL("overall"),

CONNECTED("connected"),

ONBOARDED("onboarded");

private String value;

HealthType(String value) {
this.value = value;
}

@override
public String toString() {
return String.valueOf(value);
}

@jsoncreator
public static HealthType fromValue(String text) {
for (HealthType b : HealthType.values()) {
if (String.valueOf(b.value).equals(text)) {
return b;
}
}
return null;
}
}

**Comment by ambikath** [comment]
See the same issue..Any responses?

**Comment by sdoeringNew** [comment]
Do not put a ```@JsonValue``` at the toString() method. Add a new method:
```Java
@JsonValue
public {{dataType}} getValue() {
    return value;
}
```

This will work for non-String enums, too.
Imaging enums of datatype Integer or Double.

**Comment by ambikath** [comment]
This is a generated file.
Cannot add code here.
It should be fixed from the swagger codegen

@sdoeringNew please check this 

https://github.com/swagger-api/swagger-codegen/issues/3611

**Comment by sdoeringNew** [comment]
Yeah, sure. I already fixed a similar issue for the Java code generation.

I just mean: It would be wrong to fix this issue by adding a ```@JsonValue``` at the ```toString()``` method.

**Comment by cbornet** [comment]
I think it's better to use Jackson's WRITE_ENUMS_USING_TO_STRING property

**Comment by ambikath** [comment]
@cbornet : You mean while deserializing? Could you give me an example?

**Comment by cbornet** [comment]
Eg : https://github.com/swagger-api/swagger-codegen/blob/be3cfda3cec6558249afbb975e8051e4b4e0ed78/modules/swagger-codegen/src/main/resources/Java/libraries/resteasy/JSON.mustache#L26

**Comment by focalize-maciej** [comment]
This is still an issue in 2026. Enums defined inside other objects have the `@JsonValue` annotation on toString, while those defined on the top level of the schema don't. This results in enums incorrectly serialized with uppercase using jaxrs-jersey server stub.
